### ISSUE TITLE
Unavoidable failure

### ISSUE THREAD

**Issue by dzpao** [alexkohler/dogsled#2]
I encountered a problem while using dogsled to check my source code. I use tview in my project, which has an API that returns the coordinates and height and width of the rectangle where the UI element is located. Such APIs are common in UI libraries. But my code only needs to know the height, so I have to write this code:

```
	_, _, _, height := ui.pages.GetRect()
```

But at this time dogsled told me that this was wrong. But I can’t really assign them to some variables, because I really do n’t need them!

So what should I do?

Thank you!

**Comment by alexkohler** [comment]
Hi @dzpao! 

You have a couple options:
* You may use dogsled's `-n` flag to increase the threshold of blank identifiers allowed in an assignment statement
* If using golangci-lint, you may use a `//nolint:dogsled` comment.

Feel free to reopen or reach out if you have any other problems/questions. :cowboy_hat_face:
